### ISSUE TITLE
Support Overture parquet conversion to GeoParquet

### ISSUE THREAD

**Issue by cholmes** [planetlabs/gpq#57]
The new overture maps has parquet in WKB, but when I try to convert it I get:

```
% gpq convert 20230725_211237_00132_5p54t_25816df1-b864-49c0-a9a3-a13da4f37a90 out2.parquet --from=parquet --to=geoparquet
gpq: error: encoding parquet data page: encoding not supported for type BYTE_ARRAY
```

Sample data is at https://storage.googleapis.com/open-geodata/ch/20230725_211237_00132_5p54t_3b7d7eb3-dd9c-442a-a9b9-404dc936c5d9

**Comment by cholmes** [comment]
@mtravis - funny, I just came here to make the same comment, as I had noticed that too.

Yeah, running it through DuckDB in most any way seems to work fine, so it seems to not be anything fundamental with the structure of that data.

**Comment by tschaub** [comment]
I get an error trying to read this file using the Arrow libs directly.  I've ticketed this as https://github.com/apache/arrow/issues/37968.

I'll work on trying to narrow it down.

**Comment by tschaub** [comment]
This now works in [the latest release](https://github.com/planetlabs/gpq/releases).  If using brew, you can `brew update && brew install planetlabs/tap/gpq` to install the latest.  And you can run `gpq version` to see what version you have installed.

```
# the file above is now converted to valid geoparquet
gpq convert overture.parquet --to geoparquet | gpq validate
```

**Comment by tschaub** [comment]
In case it is of interest to Overture users, I opened a discussion about the Parquet schema here: https://github.com/OvertureMaps/schema/discussions/55

Basically, the current schema for `names` and `sources` is not as specific as it could be (allowing arbitrary properties for `names` for example instead of restricting it to the `common`, `official`, `alternate`, and `short` described in the JSON Schema).  If you think a more specific schema would be harmful or helpful, please chime in.
